name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        # Tells GitHub to go into the client folder to find package.json
        working-directory: client
        run: npm install

      - name: Build Project
        # Tells GitHub to build the project inside the client folder
        working-directory: client
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          CI: false

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOLL_PROJECT_479605 }}
          channelId: live
          projectId: toll-project-479605
          # Tells Firebase to look for firebase.json inside the client folder
          entryPoint: client
